name: daily_expense_tracker
description: A simple daily expense tracker for Android
publish_to: "none"
version: 0.1.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.0+4
  path: ^1.8.0
  shared_preferences: ^2.0.15
  intl: ^0.18.0
  file_picker: ^10.3.8
  path_provider: ^2.0.15
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.2.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
